### ISSUE TITLE
ERROR: Missing field in record construction settingClientSupported

### ISSUE THREAD

**Issue by evan0greenup** [ndmitchell/hoogle#426] opened 2024-06-17 12:49 UTC
When I attempt to enter 

```bash
hoogle generate --haskell
```

It output the following
```
Starting generate
Downloading https://www.stackage.org/lts/cabal.config... hoogle: src/Input/Download.hs:(45,8)-(49,7): Missing field in record construction settingClientSupported
```

Really do not know what is going wrong.

**Comment by ozkutuk** [comment] 2024-06-29 11:24
Seems to be duplicate of https://github.com/ndmitchell/hoogle/issues/423

**Comment by ndmitchell** [comment] 2024-07-28 21:45
Closing in favor of #423.

**Closed by ndmitchell** 2024-07-28 21:45 UTC
